

services:
  mongo:
    image: mongo:8
    container_name: ims_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: ims_backend
    volumes:
      - /IMS/uploads:/app/uploads:rw 
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_URI=mongodb://mongo:27017/production
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET="production81234567"
      - DEFAULT_USER_APPROVED=true
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: ims_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongo_data: