name: Backend CI


on:
    push:
        paths:
            - 'server/**'
    pull_request:
        paths:
            - 'server/**'

jobs:
    backend-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3


            - name: Set up Nide.ja
              uses: actions/setup-node@v3
              with:
                node-version: '22'

            - name: Install dependencies
              run: npm install
              working-directory: ./server

            - name: Run backend tests
              run: npm test
              working-directory: ./server
                